# Generated by Django 6.0.2 on 2026-03-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudokus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sudoku',
            name='is_printed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sudoku',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
    ]
